### PR TITLE
Added the Firebase Android BoM to manage Firebase library versions.

### PR DESCRIPTION
**Pull request by siarhei-luskanau**

### CODE REVIEW

**Comment by siarhei-luskanau** [comment]
@nbransby Would you like to review this PR?

**Comment by nbransby** [comment]
Changing the firebase library versions is not trivial as its unlikely to prevent the build succeeding but very likely to cause crashes at runtime, I assume you added `getThread` to fix one of thoses crashes - problem is the test coverage is not currently high enough to catch all likely crashes without additional manual testing.

One possible solution would be to merge this in and do an alpha release to crowdsource the testing.

**Comment by siarhei-luskanau** [comment]
> Changing the firebase library versions is not trivial as its unlikely to prevent the build succeeding but very likely to cause crashes at runtime, I assume you added `getThread` to fix one of thoses crashes - problem is the test coverage is not currently high enough to catch all likely crashes without additional manual testing.
> 
> One possible solution would be to merge this in and do an alpha release to crowdsource the testing.

Thank you for response. You are right, this changes aren't tested at runtime.
I propose use tested version of Firebase BoM 32.7.0.

And next step can be alpha release with the latest Firebase BoM version

**Comment by nbransby** [comment]
Are all the Firebase BoM 32.7.0 versions equal to or less than the one we specified before this PR?

**Comment by siarhei-luskanau** [comment]
> Are all the Firebase BoM 32.7.0 versions equal to or less than the one we specified before this PR?

Yes. The Firebase libraries version are listed in POM file https://dl.google.com/android/maven2/com/google/firebase/firebase-bom/32.7.0/firebase-bom-32.7.0.pom


All firebase-bom versions can be found at https://maven.google.com/web/index.html?q=bom#com.google.firebase:firebase-bom

**Comment by nbransby** [comment]
would be a lot easier to see whats changes after a review if you didn't force push all the time ;)

**Review by nbransby — APPROVED** [review]

**Pull request merged**
